const invoice = require('./invoice.json')
const invoiceReceipt = require('./invoiceReceipt.json')
const promiseOfPayment = require('./promiseOfPayment.json')
const paymentRequest = require('./paymentRequest.json')
const escrowContract = require('./escrowContract.json')
const pickupRequest = require('./pickupRequest.json')
const pickupReceipt = require('./pickupReceipt.json')
const proofOfDelivery = require('./proofOfDelivery.json')
const merchantDispute = require('./merchantDispute.json')
const disputeReceipt = require('./disputeReceipt.json')
const merchantCancellation = require('./merchantCancellation.json')
const consumerCancellation = require('./consumerCancellation.json')

exports.invoice = invoice
exports.invoiceReceipt = invoiceReceipt
exports.promiseOfPayment = promiseOfPayment
exports.paymentRequest = paymentRequest
exports.escrowContract = escrowContract
exports.pickupRequest = pickupRequest
exports.pickupReceipt = pickupReceipt
exports.proofOfDelivery = proofOfDelivery
exports.merchantDispute = merchantDispute
exports.disputeReceipt = disputeReceipt
exports.merchantCancellation = merchantCancellation
exports.consumerCancellation = consumerCancellation
